# Generated by Django 5.0.4 on 2024-04-07 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bill_billitem_delete_employee_bill_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='products',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='price',
        ),
        migrations.AddField(
            model_name='billitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.bill'),
        ),
    ]
